Add Note for character limit of function path in events
zappa/Zappa pull request #1189
Opened 2022-11-14 11:15 UTC by DilLip-Chowdary-Codes

## Description
 
Add Note for `function` path in `events`, as it will raise an error if the character length exceeds.
## GitHub Issues

2022-11-19 01:13 UTC, monkut requested changes

2022-11-19 01:13 UTC, monkut commented on README.md
> +**Note:** `function` path should not exceed 64 characters.
should not -> cannot

2022-11-19 04:22 UTC, DilLip-Chowdary-Codes reviewed
updated according to review inputs

2024-09-30 01:57 UTC, monkut approved these changes

2024-09-30 05:10 UTC, DilLip-Chowdary-Codes reviewed
Branch Synced with parent

2025-03-18 04:35 UTC, monkut approved these changes

2025-04-15 00:54 UTC, merged