Handle missing field requestContext
zappa/Zappa pull request #972
Opened 2021-04-29 09:06 UTC by pauldes

Systems calling the Lambda (other than API Gateway) may not provide the field requestContext in the event. This commit makes the code robust to this case.

2021-04-29 12:26 UTC, techdragon requested changes
I know its a little detail, but this might be better if it's more explicit. To be laser focused on the "this key needs to be in the `event_info` dictionary". I think `if "requestContext" in event_info:` might be the better way to declare these conditionals.

2021-05-01 15:41 UTC, pauldes commented
@techdragon done, thanks for the review

2022-03-23 13:43 UTC, LucasHartridge commented
Hey guys :wave: Can we fix conflicts and merge this one?

2023-04-24 12:07 UTC, hellno requested changes
hi @pauldes, just going through open PRs and doing some housekeeping.
Do you want to fix the merge conflicts to get this into main branch? 😊

2023-04-24 12:17 UTC, pauldes commented
Hi @hellno, I'll pass.

2023-08-16 06:44 UTC, monkut commented
declined to merged (and appears to be implemented to some degree already)
closing.

2023-08-16 06:44 UTC, closed without merging